name: fl_language_picker
description: It makes language select pickers for you in Flutter. You can use it freely in lots of ways.
version: 0.0.1
homepage: https://github.com/gomgom/flutter_language_pickers

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0

#flutter:
#  assets:
#  - assets/
